version: '3.4'

networks:
  selfieburguerapp:

services:
  mssqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks: 
      - selfieburguerapp
    entrypoint: /bin/bash

  selfieburguerdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssqlserver
    hostname: mssqls-server
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      - ./:/usr/src/app 
    working_dir: /usr/src/app 
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong@Passw0rd
      DATABASE_NAME: master
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_LOG_DIR: /var/opt/mssql/log
      MSSQL_BACKUP_DIR: /var/opt/mssql/backup
      MSSQL_SSL_KEY: /var/opt/mssql/certs/key.pem
      MSSQL_SSL_CERT: /var/opt/mssql/certs/cert.pem
    networks:
      - selfieburguerapp
    volumes_from:
      - mssqldata

  selfieburguer.api:
    container_name: selfie-burguer-app
    image: ${DOCKER_REGISTRY-}selfieburguerapi
    build:
      context: .
      dockerfile: SelfieBurguer.API/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - selfieburguerdb
    environment:
      - DB_HOST=selfieburguerdb
      - DB_NAME=SelfieBurguerApp
      - DB_SA_PASSWORD=YourStrong@Passw0rd
    networks:
      - selfieburguerapp