version: '3.4'

networks:
  selfieburguerapp:

services:
  selfieburguerdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_LOG_DIR=/var/opt/mssql/log
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
      - MSSQL_SSL_KEY=/var/opt/mssql/certs/key.pem
      - MSSQL_SSL_CERT=/var/opt/mssql/certs/cert.pem
    volumes:
      - ./key.pem:/var/opt/mssql/certs/key.pem
      - ./cert.pem:/var/opt/mssql/certs/cert.pem
    networks:
      - selfieburguerapp
  
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - selfieburguerdb
    volumes:
      - ./init.sql:/tmp/init.sql
      - ./init.sh:/tmp/init.sh
    command: /bin/bash ./tmp/init.sh

  selfieburguer.api:
    container_name: selfie-burguer-app
    image: ${DOCKER_REGISTRY-}selfieburguerapi
    build:
      context: .
      dockerfile: SelfieBurguer.API/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - selfieburguerdb
    environment:
      - DB_HOST=selfieburguerdb
      - DB_NAME=SelfieBurguerApp
      - DB_SA_PASSWORD=YourStrong@Passw0rd
    networks:
      - selfieburguerapp