apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfie-app
  template:
    metadata:
      labels:
        app: selfie-app
    spec:
      containers:
        - name: selfie-app
          image: leonardev/selfieburguerapi:latest  # Use a imagem correta do seu registro
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mssql-service
            - name: DB_NAME
              value: SelfieBurguerApp
            - name: DB_SA_PASSWORD
              value: YourStrong@Passw0rd
