apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: selfie-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32386
  type: NodePort
