apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssqldata
          image: leonardev/custom-mssql:latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: YourStrong@Passw0rd
            - name: MSSQL_DATA_DIR
              value: /var/opt/mssql/data
            - name: MSSQL_LOG_DIR
              value: /var/opt/mssql/log
            - name: MSSQL_BACKUP_DIR
              value: /var/opt/mssql/backup
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          emptyDir: {}
